name: Build Dependent Standard Libraries

on:
    workflow_dispatch:
        inputs:
            timestamped_version:
                description: Module timestamped version
                required: false
                default: ''
            target_branch:
                description: Target branch of the dependent module
                required: false
                default: ''
            ballerina_modules:
                description: Dependent Ballerina modules
                required: false
                default: "['cache', 'http', 'grpc', 'websocket', 'graphql']"
            ballerinax_modules:
                description: Dependent Ballerina extended modules
                required: false
                default: "['rabbitmq', 'nats', 'kafka']"
            additional_build_options:
                description: Additional build options
                required: false
                default: ""

jobs:
    build-ballerina-modules:
        if: inputs.ballerina_modules != ''
        name: Build Ballerina Module
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                module: ${{ fromJson(inputs.ballerina_modules) }}
        steps:
            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: 11

            - name: Checkout module
              uses: actions/checkout@v3
              if: ${{ inputs.timestamped_version == '' }}

            - name: Change to Timestamped Version
              if: ${{ inputs.timestamped_version == '' }}
              run: |
                  startTime=$(TZ="Asia/Kolkata" date +'%Y%m%d-%H%M00')
                  latestCommit=$(git log -n 1 --pretty=format:"%h")
                  VERSION=$((grep -w 'version' | cut -d= -f2) < gradle.properties | rev | cut --complement -d- -f1 | rev)
                  updatedVersion=$VERSION-$startTime-$latestCommit
                  echo TIME_STAMPED_VERSION=$updatedVersion
                  echo TIME_STAMPED_VERSION=$updatedVersion >> $GITHUB_ENV
                  sed -i "s/version=\(.*\)/version=$updatedVersion/g" gradle.properties

            - name: Build Timestamped version
              if: ${{ inputs.timestamped_version == '' }}
              env:
                  packageUser: ${{ github.actor }}
                  packagePAT: ${{ secrets.GITHUB_TOKEN }}
              run: ./gradlew clean build publishToMavenLocal -x test

            - name: Checkout dependent Ballerina module
              uses: actions/checkout@v3
              id: checkout
              if: ${{ inputs.target_branch != '' }}
              continue-on-error: true
              with:
                  repository: 'ballerina-platform/module-ballerina-${{ matrix.module }}'
                  ref: ${{ inputs.target_branch }}

            - name: Checkout default branch
              uses: actions/checkout@v3
              if: ${{ inputs.target_branch == '' || steps.checkout.outcome == 'failure' }}
              continue-on-error: true
              with:
                  repository: 'ballerina-platform/module-ballerina-${{ matrix.module }}'

            - name: Change constraint module version
              run: |
                  if ${{ inputs.timestamped_version != ''}}; then
                      CONSTRAINT_VERSION=${{ inputs.timestamped_version }}
                  else
                      CONSTRAINT_VERSION=${{ env.TIME_STAMPED_VERSION }}
                  fi
                  echo CONSTRAINTVERSION=$CONSTRAINT_VERSION
                  sed -i "s/stdlibConstraintVersion=\(.*\)/stdlibConstraintVersion=$CONSTRAINT_VERSION/g" gradle.properties
            - name: Build with Gradle
              env:
                  packageUser: ${{ github.actor }}
                  packagePAT: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  ./gradlew clean build ${{ inputs.additional_build_options }}
    build-ballerinax-modules:
        if: inputs.ballerinax_modules != ''
        name: Build Ballerina Extended Module
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                module: ${{ fromJson(inputs.ballerinax_modules) }}
        steps:
            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: 11

            - name: Checkout module
              uses: actions/checkout@v3
              if: ${{ inputs.timestamped_version == '' }}

            - name: Change to Timestamped Version
              if: ${{ inputs.timestamped_version == '' }}
              run: |
                  startTime=$(TZ="Asia/Kolkata" date +'%Y%m%d-%H%M00')
                  latestCommit=$(git log -n 1 --pretty=format:"%h")
                  VERSION=$((grep -w 'version' | cut -d= -f2) < gradle.properties | rev | cut --complement -d- -f1 | rev)
                  updatedVersion=$VERSION-$startTime-$latestCommit
                  echo TIME_STAMPED_VERSION=$updatedVersion
                  echo TIME_STAMPED_VERSION=$updatedVersion >> $GITHUB_ENV
                  sed -i "s/version=\(.*\)/version=$updatedVersion/g" gradle.properties

            - name: Build Timestamped version
              if: ${{ inputs.timestamped_version == '' }}
              env:
                  packageUser: ${{ github.actor }}
                  packagePAT: ${{ secrets.GITHUB_TOKEN }}
              run: ./gradlew clean build publishToMavenLocal -x test

            - name: Checkout dependent Ballerina extended module
              uses: actions/checkout@v3
              id: checkout
              if: ${{ inputs.target_branch != '' }}
              continue-on-error: true
              with:
                  repository: 'ballerina-platform/module-ballerinax-${{ matrix.module }}'
                  ref: ${{ inputs.target_branch }}

            - name: Checkout default branch
              uses: actions/checkout@v3
              if: ${{ inputs.target_branch == '' || steps.checkout.outcome == 'failure' }}
              continue-on-error: true
              with:
                  repository: 'ballerina-platform/module-ballerinax-${{ matrix.module }}'

            - name: Change constraint module version
              run: |
                  if ${{ inputs.timestamped_version != ''}}; then
                      CONSTRAINT_VERSION=${{ inputs.timestamped_version }}
                  else
                      CONSTRAINT_VERSION=${{ env.TIME_STAMPED_VERSION }}
                  fi
                  echo CONSTRAINTVERSION=$CONSTRAINT_VERSION
                  sed -i "s/stdlibConstraintVersion=\(.*\)/stdlibConstraintVersion=$CONSTRAINT_VERSION/g" gradle.properties
            - name: Build with Gradle
              env:
                  packageUser: ${{ github.actor }}
                  packagePAT: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  ./gradlew clean build ${{ inputs.additional_build_options }}
